apiVersion: v1
kind: Service
metadata:
  name: apuestas-service
  labels:
    app: apuestas-service
spec:
  type: ClusterIP # ¡Crucial! No debe ser LoadBalancer
  selector:
    app: apuestas-service # Debe coincidir con el label del Deployment
  ports:
    - protocol: TCP
      port: 8005       # Puerto que usarán los otros servicios para llamar al servicio
      targetPort: 8005 # Puerto que escucha tu aplicación en el pod